# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 01:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_remove_contact_user_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user_from',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='rel_from_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
